version: '3.4'

services:

  hospitalapi:
    build:
      dockerfile: Stacks/Build/Hospital/Dockerfile
      context: ../
    ports:  
      - "8088:80"
    restart: on-failure
    depends_on:
      - hospitaldb
    environment:
      HOSPITAL_DB_PATH: "host=hospitaldb;port=5432;database=HOSPITAL;username=postgres;password=postgres"

  hospitaldb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "HOSPITAL"
    ports:
      - 5454:5432
