version: '3.4'

services:

  integrationapi:
    build:
      dockerfile: Stacks/Build/Integration/Dockerfile
      context: ../
    ports:  
      - "8090:80"
    restart: on-failure
    depends_on:
      - integrationdb
      - rabbitmq
    environment:
      INTEGRATION_DB_PATH: "host=integrationdb;port=5432;database=INTEGRATION;username=postgres;password=postgres"
      RABBITMQ_HOST: "rabbitmq"

  integrationdb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "INTEGRATION"
    ports:
      - 5456:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
