name: Run Hospital End to End Tests

on:
  pull_request:
    branches: [master, development]

env:
  PROJECT_PATH_HOSPITAL: './Hospital'
  PROJECT_PATH_INTEGRATION: './Integration'
  DB_PATH: 'Host=postgres;Database=HOSPITAL;Username=postgres;Password=postgres'
  DB_PATH_INTEGRATION: 'Host=postgres;Database=INTEGRATION;Username=postgres;Password=postgres'

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
      rabbitmq:
        image: rabbitmq:3-management-alpine

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Restore NuGet packages
        run: |
          dotnet restore ${{ env.PROJECT_PATH_HOSPITAL }}
          dotnet restore ${{ env.PROJECT_PATH_INTEGRATION }}

      - name: Build
        run: |
          dotnet build ${{ env.PROJECT_PATH_HOSPITAL }}
          dotnet build ${{ env.PROJECT_PATH_INTEGRATION }}

      - name: Start
        env:
          HOSPITAL_DB_PATH: ${{ env.DB_PATH }}
          INTEGRATION_DB_PATH: ${{ env.DB_PATH_INTEGRATION }}
          RABBITMQ_HOST: 'rabbitmq'
        run: |
          dotnet run --project Hospital/HospitalApi/ --urls=http://localhost:44303 &
          dotnet run --project Integration/IntegrationApi/ --urls=http://localhost:44302 &

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install npm dependencies for web-client
        working-directory: ./WebClients/PatientWebClient
        run: npm ci

      - name: Build web-client
        working-directory: ./WebClients/PatientWebClient
        run: npm run start &

      - name: Sleep for 15 seconds
        run: sleep 15s

      - name: Test
        env:
          HOSPITAL_DB_PATH: ${{ env.DB_PATH }}
          INTEGRATION_DB_PATH: ${{ env.DB_PATH_INTEGRATION }}
        run: dotnet test ${{ env.PROJECT_PATH_HOSPITAL }}/SeleniumTests
