name: Run Hospital Integration Tests

on:
  pull_request:
    branches: [master, development]
    paths:
      - 'Hospital/**'

env:
  DOTNET_VERSION: '5.0.x'
  HOSPITAL_SOLUTION_PATH: './Hospital'
  HOSPITAL_API_PATH: './Hospital/HospitalApi'
  HOSPITAL_INTEGRATION_TESTS_PATH: './Hospital/HospitalIntegrationTests'

jobs:
  build-and-run-integration-tests:
    name: Build and Run Hospital Integration Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:3.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start dependencies (docker-compose)
        working-directory: Stacks
        run: docker-compose -f hospital-integration-tests-docker-compose.yml up -d

      - name: Install dependencies
        run: dotnet restore ${{ env.HOSPITAL_SOLUTION_PATH }}

      - name: Build
        run: dotnet build --configuration Release --no-restore ${{ env.HOSPITAL_SOLUTION_PATH }}

      - name: Run Hospital Api
        working-directory: ${{ env.HOSPITAL_API_PATH }}
        run: dotnet run

      - name: Run Integration Tests
        run: dotnet test --no-restore --verbosity normal ${{ env.HOSPITAL_INTEGRATION_TESTS_PATH }}
